version: 0.2

run-as: root

env:
  variables:
    build_version: "0.1"

phases:
  install:
    commands:
      - echo "Installing software to Ubuntu"
      - apt-get update
      - apt-get -y install python3.7 python3-pip
      - pip3 install geneticalgorithm
  pre_build:
    commands:
      - echo "Running pre_build"
      - mkdir eoin
      - ls -lh
  build:
    commands:
      - echo "Building the application"
      - echo "test" > eoin/eoin.txt

artifacts:
  files:
    - eoin/eoin.txt