version: 0.2

run-as: root

env:
  variables:
    build_version: "0.1"

phases:
  install:
    commands:
      - apt-get update
      - apt-get install python3.7 pip3
      - pip3 install geneticalgorithm
  pre_build:
    commands:
      - echo "Running pre_build"
      - mkdir eoin
      - echo "test" > eoin/eoin.txt
  build:
    commands:
      - echo "Building the application"

artifacts:
  files:
    - eoin/eoin.txt