version: 0.2

run-as: root

env:
  variables:
    build_version: "0.1"

phases:
  install:
    commands:
      - apt update
      - apt install python3.7
#    runtime-versions:
#      python: 3.x
  pre_build:
    commands:
      - echo "Running pre_build"
      - mkdir eoin
      - echo "test" > eoin/eoin.txt
  build:
    commands:
      - echo "Building the application"

artifacts:
  files:
    - eoin/eoin.txt